### ISSUE TITLE
Syllabi access

### ISSUE THREAD

**Issue by Artachtron** [world-class/binary-assets#9]
I don't know if the problem is on my end, but I can't access certain syllabi like this one: https://github.com/world-class/binary-assets/blob/master/modules/syllabi/Syllabus_CM2035_ADS2.pdf

I cloned the repo and realize it was in it, so only the access is not working.  

Github servers seems ok, and most of syllabi are accessible. I do not know how to fix that type of issue myself.

**Comment by sglavoie** [comment]
@Artachtron thank you for raising this issue.

I can reproduce the issue in Google Chrome 100.0.4896.60, although it works fine in Firefox 98.0.1. So I suspect this is a rendering issue on the webpage only as both browsers are able to read the PDF and other external PDF readers like Preview or Adobe Acrobat can also open it alright.

For now, I'm afraid this is a GitHub-related thing and I have no resolution to offer. I've checked that this PDF is exactly the same as the one provided by the university in the orientation module on Coursera. I'll let you know if/once I know more about this. 😃

**Comment by sglavoie** [comment]
I was just about to file an issue with GitHub, but then I inspected the Network tab in the Developer Tools in Chrome and realized that a script was being blocked by the extension **uBlock Origin**. Could you check whether that's the cause for you, too? In my case, disabling uBlock Origin on GitHub resolves this issue fully on my end. 👍

**Comment by Artachtron** [comment]
I tried deactivating my both extensions: Adguard Adblocker and Avira Web protection and it worked. 👍 It seems like if one of them is active it does not work, so apparently they both block it.

It only happens with ADS1 and ADS2 (on the level 4 and 5 modules.) 🤔

**Comment by sglavoie** [comment]
@Artachtron glad it worked! It's not a perfect solution, but there is not much we can do in the context of this repository to solve it otherwise.

This is something related to how GitHub tries to fetch statistics when accessing certain pages (explaining to some extent why it happens on some pages and not others), although I can't pretend to know what is really going on behind the scenes. But in short, this is merely GitHub-specific and the affected PDFs are valid in the end. 🤷 

This will remain a minor inconvenience for the time being as hosting these files somewhere else is currently not an option being considered. But if there's a better way to do it, we'll be listening! 😄
